version: 2

workflows:
  version: 2
  build:
    jobs:
      - install_and_build
      - deploy:
          requires:
            - install_and_build
          filters:
            branches:
              only:
                - master
                - dev

jobs:
  install_and_build:
    working_directory: ~/stockflux
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout:
          path: ~/stockflux
      - run:
          name: Build Core
          command: |
            cd ~/stockflux/stockflux-core
            npm ci
            npm run build
      - run:
          name: Build Components
          command: |
            cd ~/stockflux/stockflux-components
            npm ci
            npm run build
      - run:
          name: Build BitFlux
          command: |
            cd ~/stockflux/stockflux-bitflux
            npm ci
            npm run build
      - run:
          name: Build Chart
          command: |
            cd ~/stockflux/stockflux-chart
            npm ci
            npm run build
      - run:
          name: Build Container
          command: |
            cd ~/stockflux/stockflux-container
            npm ci
            npm run build
      - run:
          name: Build News
          command: |
            cd ~/stockflux/stockflux-news
            npm ci
            npm run build
      - run:
          name: Build Watchlist
          command: |
            cd ~/stockflux/stockflux-watchlist
            npm ci
            npm run build
      - run:
          name: Build launcher
          command: |
            cd ~/stockflux/stockflux-launcher
            npm ci
            npm run build
      - persist_to_workspace:
          root: ~/stockflux
          paths: .

  deploy:
    working_directory: ~/stockflux
    docker:
      - image: circleci/python:3.7.2
    steps:
      - attach_workspace:
          at: ~/stockflux
      - add_ssh_keys:
          fingerprints:
            - "e1:6c:ab:38:9e:8f:ed:f1:60:4a:c7:b1:23:33:0c:07"
            - "16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48" # GitHub RSA
            - "ad:1c:08:a4:40:e3:6f:9c:f5:66:26:5d:4b:33:5d:8c" # GitHub DSA
      - run:
          name: Add GitHub SSH fingerprints to known hosts
          command: |
            # https://serverfault.com/questions/447028/non-interactive-git-clone-ssh-fingerprint-prompt
            # Grabbed GitHub's public key by running ssh-keyscan github.com
            # locally and directing it to the github_key file. Adding this key
            # to known hosts (creating it if it doesn't exist) prevents the
            # prompt that warns about the authenticity of the host when trying
            # to push tags, that causes the build to hang until it times out.
            cd ~/stockflux/.circleci
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            echo $(cat github_key) >> ~/.ssh/known_hosts
      - run:
          name: Version package.json files
          command: |
            cd .circleci
            echo $(python version.py \
              stockflux-launcher \
              stockflux-container \
              stockflux-chart \
              stockflux-news \
              stockflux-watchlist) >> ~/stockflux/version
      - run:
          name: Install AWS CLI
          command: pip install awscli --user --upgrade
      - run:
          name: Upload Artifacts to S3
          command: |
            cd ~/stockflux
            STOCKFLUX_VERSION=$(cat ~/stockflux/version)
            BUCKET="stockflux-public-$CIRCLE_BRANCH"
            ~/.local/bin/aws s3 sync \
              stockflux-chart/build \
              "s3://$BUCKET/artifacts/stockflux-chart/$STOCKFLUX_VERSION/" \
              --delete
            ~/.local/bin/aws s3 sync \
              stockflux-container/build \
              "s3://$BUCKET/artifacts/stockflux-container/$STOCKFLUX_VERSION/" \
              --delete
            ~/.local/bin/aws s3 sync \
              stockflux-news/build \
              "s3://$BUCKET/artifacts/stockflux-news/$STOCKFLUX_VERSION/" \
              --delete
            ~/.local/bin/aws s3 sync \
              stockflux-watchlist/build \
              "s3://$BUCKET/artifacts/stockflux-watchlist/$STOCKFLUX_VERSION/" \
              --delete
            ~/.local/bin/aws s3 sync \
              stockflux-launcher/build \
              "s3://$BUCKET/artifacts/stockflux-launcher/$STOCKFLUX_VERSION/" \
              --delete
      - run:
          name: Tag GitHub with new version
          command: |
            STOCKFLUX_VERSION=$(cat ~/stockflux/version)
            rm ~/stockflux/version
            git tag "$STOCKFLUX_VERSION"
            git push --tags
          
