version: 2

workflows:
  version: 2
  build:
    jobs:
      - install_and_build
      - deploy:
          requires:
            - install_and_build
          filters:
            branches:
              only:
                - master

jobs:
  install_and_build:
    working_directory: ~/stockflux
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout:
          path: ~/stockflux
      - run:
          name: Root package install
          command: npm ci
      - run:
          name: Bootstrap packages
          command: npm run bootstrap
      - run:
          name: Build packages
          command: npm run build
      - persist_to_workspace:
          root: ~/stockflux
          paths: .
  deploy:
    working_directory: ~/stockflux
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - attach_workspace:
          at: ~/stockflux
      - run:
          name: Install AWS CLI
          command: pip install awscli --user --upgrade
      - run:
          name: Upload chart
          command: ~/.local/bin/aws s3 sync packages/stockflux-chart/build "s3://stockflux-public--$CIRCLE_BRANCH/artifacts/stockflux-chart/13.0.0/" --delete
      - run:
          name: Upload container
          command: ~/.local/bin/aws s3 sync packages/stockflux-container/build "s3://stockflux-public--$CIRCLE_BRANCH/artifacts/stockflux-container/13.0.0/" --delete
      - run:
          name: Upload news
          command: ~/.local/bin/aws s3 sync packages/stockflux-news/build "s3://stockflux-public--$CIRCLE_BRANCH/artifacts/stockflux-news/13.0.0/" --delete
      - run:
          name: Upload watchlist
          command: ~/.local/bin/aws s3 sync packages/stockflux-watchlist/build "s3://stockflux-public--$CIRCLE_BRANCH/artifacts/stockflux-watchlist/13.0.0/" --delete
      - run:
          name: Upload launcher
          command: ~/.local/bin/aws s3 sync packages/stockflux-launcher/build "s3://stockflux-public--$CIRCLE_BRANCH/artifacts/stockflux-launcher/13.0.0/" --delete

