version: 2

workflows:
  version: 2
  build:
    jobs:
      - install_and_build
      - deploy:
          requires:
            - install_and_build
          filters:
            branches:
              only:
                - master

jobs:
  install_and_build:
    working_directory: ~/stockflux
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout:
          path: ~/stockflux
      - run:
          name: Node.js and NPM versions
          command: |
            node -v
            npm -v
      - run:
          name: Build Core
          command: |
            cd ~/stockflux/stockflux-core
            npm install
            npm run build
      - run:
          name: Build Components
          command: |
            cd ~/stockflux/stockflux-components
            npm install
            npm run build
      - run:
          name: Build BitFlux
          command: |
            cd ~/stockflux/stockflux-bitflux
            npm install
            npm run build
      - run:
          name: Build Container
          command: |
            cd ~/stockflux/stockflux-container
            npm install
            npm run build
      - run:
          name: Build Chart
          command: |
            cd ~/stockflux/stockflux-chart
            npm install
            npm run build
      - run:
          name: Build News
          command: |
            cd ~/stockflux/stockflux-news
            npm install
            npm run build
      - run:
          name: Build Watchlist
          command: |
            cd ~/stockflux/stockflux-watchlist
            npm install
            npm run build
      - run:
          name: Build launcher
          command: |
            cd ~/stockflux/stockflux-launcher
            npm install
            npm run build
      - persist_to_workspace:
          root: ~/stockflux
          paths: .
  deploy:
    working_directory: ~/stockflux
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - attach_workspace:
          at: ~/stockflux
      - run:
          name: Install AWS CLI
          command: pip install awscli --user --upgrade
      - run:
          name: Upload chart
          command: ~/.local/bin/aws s3 sync stockflux-chart/build "s3://stockflux-public-$CIRCLE_BRANCH/artifacts/stockflux-chart/13.0.0/" --delete
      - run:
          name: Upload container
          command: ~/.local/bin/aws s3 sync stockflux-container/build "s3://stockflux-public-$CIRCLE_BRANCH/artifacts/stockflux-container/13.0.0/" --delete
      - run:
          name: Upload news
          command: ~/.local/bin/aws s3 sync stockflux-news/build "s3://stockflux-public-$CIRCLE_BRANCH/artifacts/stockflux-news/13.0.0/" --delete
      - run:
          name: Upload watchlist
          command: ~/.local/bin/aws s3 sync stockflux-watchlist/build "s3://stockflux-public-$CIRCLE_BRANCH/artifacts/stockflux-watchlist/13.0.0/" --delete
      - run:
          name: Upload launcher
          command: ~/.local/bin/aws s3 sync stockflux-launcher/build "s3://stockflux-public-$CIRCLE_BRANCH/artifacts/stockflux-launcher/13.0.0/" --delete

